version: '3.8'

services:
  basler_ros_driver_pkg:           # <-- YOUR TODO: change to name of your repository
    # depends_on: 
      # - master          
      # - <package>          # <-- YOUR TODO: change dependencies to other packages
    build:
      context: .  
      dockerfile: Dockerfile
    image: basler_ros_driver_pkg:latest        # <-- YOUR TODO: change to name of your repository
    restart: unless-stopped
    environment:
      - PACKAGE_NAME=basler_ros_driver_pkg     # <-- YOUR TODO: change to name of your repository
      # - ROS_MASTER_URI=http://master:11311 
    volumes:
      - ./:/ws/src/basler_ros_driver_pkg       # <-- YOUR TODO: change to name of your repository
      - ./dragandbot_common:/ws/src/dragandbot_common
    privileged: true
    entrypoint: chmod +x /ws/src/basler_ros_driver_pkg/docker-entrypoint.sh && /ws/src/basler_ros_driver_pkg/docker-entrypoint.sh  # <-- YOUR TODO: change to name of your repository
    command: sh -c "while true; do sleep 1; done"    
# networks:
#   ros_network:
#     driver: bridge
